import { IHero } from '../../../interfaces';

export const heroes: IHero[] = [
  {
    heroName: 'Spiderman',
    realName: 'Peter Parker',
    studio: 'Marvel',
    gender: 'Male',
    image: 'https://domain.com/image.jpg',
    nationality: 'American',
    powers: 'Strength, Speed, Reflexes, Durability, Spider-Sense, Wallcrawling',
  },
  {
    heroName: 'Ironman',
    realName: 'Tony Stark',
    studio: 'Marvel',
    gender: 'Male',
    image: 'https://domain.com/image.jpg',
    nationality: 'American',
    powers: 'Intelligence',
  },
  {
    heroName: 'Captain America',
    realName: 'Steve Rogers',
    studio: 'Marvel',
    gender: 'Male',
    image: 'https://domain.com/image.jpg',
    nationality: 'American',
    powers: 'Strength, Speed, Reflexes, Durability',
  },
  {
    heroName: 'Super Man',
    realName: 'Clark Kent',
    studio: 'DC',
    gender: 'Male',
    image: 'https://domain.com/image.jpg',
    nationality: 'Kryptonian',
    powers: 'Strength, Super Speed, Reflexes, Durability, Eyes Laser, Fly',
  },
  {
    heroName: 'Batman',
    realName: 'Bruce Wayne',
    studio: 'DC',
    gender: 'Male',
    image: 'https://domain.com/image.jpg',
    nationality: 'American',
    powers: 'Intelligence',
  },
  {
    heroName: 'Wonder Woman',
    realName: 'Princes Diana',
    studio: 'DC',
    gender: 'Female',
    image: 'https://domain.com/image.jpg',
    nationality: 'Amazon',
    powers: 'Strength, Super Speed, Reflexes, Durability, Sensuality',
  },
];